trigger:
  - main
  - develop
  - patch/*

pr:
  - main
  - develop
  - patch/*

parameters:
  - name: buildExternals
    displayName: 'The specific native artifacts to use for this build.'
    type: number
    default: 0
  - name: VM_IMAGE_HOST
    type: object
    default:
      pool:
        name: Azure Pipelines
        vmImage: ubuntu-18.04
  - name: VM_IMAGE_WINDOWS
    type: object
    default:
      pool:
        name: Azure Pipelines
        vmImage: windows-2022
  - name: VM_IMAGE_MAC_NATIVE
    type: object
    default:
      pool:
        name: Azure Pipelines
        vmImage: macos-11
  - name: VM_IMAGE_MAC
    type: object
    default:
      pool:
        name: Azure Pipelines
        vmImage: macos-12
  - name: VM_IMAGE_LINUX
    type: object
    default:
      pool:
        name: Azure Pipelines
        vmImage: ubuntu-18.04

pool:
  name: Azure Pipelines
  vmImage: ubuntu-18.04

variables:
  - template: azure-pipelines-variables.yml

jobs:
  - job: testing
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-20.04
    steps:
      - pwsh: |
          dir env:
          echo "all:"
          git diff-tree --no-commit-id --name-only -r HEAD~ HEAD
          echo "native:"
          git diff-tree --no-commit-id --name-only -r HEAD~ HEAD native
          echo "scripts:"
          git diff-tree --no-commit-id --name-only -r HEAD~ HEAD scripts
          echo "-"
          