trigger:
  - main
  - develop
  - patch/*

pr:
  - main
  - develop
  - patch/*

parameters:
  - name: buildExternals
    displayName: 'The specific native artifacts to use for this build.'
    type: number
    default: 5836456
  - name: VM_IMAGE_WINDOWS
    type: object
    default:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesWindows2022compliant
  - name: VM_IMAGE_MAC
    type: object
    default:
      name: Azure Pipelines
      vmImage: internal-macos-11
  - name: VM_IMAGE_LINUX
    type: object
    default:
      name: AzurePipelines-EO
      vmImage: AzurePipelinesUbuntu18.04compliant

variables:
  - template: azure-pipelines-variables.yml

resources:
  repositories:
    - repository: xamarin-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main

stages:
  - template: azure-templates-stages.yml
    parameters:
      isBuildPipeline: true
      buildExternals: ${{ parameters.buildExternals }}
      VM_IMAGE_WINDOWS: ${{ parameters.VM_IMAGE_WINDOWS }}
      VM_IMAGE_MAC: ${{ parameters.VM_IMAGE_MAC }}
      VM_IMAGE_LINUX: ${{ parameters.VM_IMAGE_LINUX }}
